/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.table.DefaultTableModel;
import modelo.Categoria;

/**
 *
 * @author DEEPGAMING
 */
public class GestionPalabras extends javax.swing.JFrame {

    public DefaultTableModel modeloTabla;

    private int longitud;

    /**
     * Creates new form GestionPalabras
     */
    public GestionPalabras() {
        this(5);
    }

    public GestionPalabras(int longitud) {
        this.longitud = longitud;
        initComponents();
        String[] columnas = {"ID", "Palabra", "Categoría", "Dificultad"};
        modeloTabla = new DefaultTableModel(columnas, 0);
        jTablePalabras.setModel(modeloTabla);
        for (int i = 1; i <= 5; i++) {
            jComboBoxDificultad.addItem(i);
        }
        jComboBoxDificultad.setSelectedItem(3);
        setTitle("Gestión de Palabras de " + longitud + " letras");
        jLabelTitulo.setText("PALABRAS DE " + longitud + " LETRAS");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTablePalabras = new javax.swing.JTable();
        panelForm = new javax.swing.JPanel();
        jLabelPalabra = new javax.swing.JLabel();
        jTextFieldPalabra = new javax.swing.JTextField();
        jLabelCategoria = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelDificultad = new javax.swing.JLabel();
        jComboBoxDificultad = new javax.swing.JComboBox<>();
        jButtonAñadir = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Palabras");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(60, 90, 150));
        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("PALABRAS");
        jLabelTitulo.setOpaque(true);
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        jTablePalabras.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTablePalabras.setRowHeight(24);
        jScrollPaneTabla.setViewportView(jTablePalabras);
        getContentPane().add(jScrollPaneTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 680, 280));

        panelForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la palabra"));
        panelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPalabra.setText("Palabra:");
        panelForm.add(jLabelPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 60, 25));

        jTextFieldPalabra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelForm.add(jTextFieldPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 30, 140, 28));

        jLabelCategoria.setText("Categoría:");
        panelForm.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 30, 70, 25));

        panelForm.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 30, 160, 28));

        jLabelDificultad.setText("Dificultad:");
        panelForm.add(jLabelDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 30, 70, 25));

        panelForm.add(jComboBoxDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 30, 100, 28));

        getContentPane().add(panelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 680, 75));

        jButtonAñadir.setBackground(new java.awt.Color(70, 140, 70));
        jButtonAñadir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonAñadir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAñadir.setText("Añadir");
        jButtonAñadir.setFocusPainted(false);
        getContentPane().add(jButtonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 425, 130, 40));

        jButtonModificar.setBackground(new java.awt.Color(60, 90, 150));
        jButtonModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("Modificar");
        jButtonModificar.setFocusPainted(false);
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 425, 130, 40));

        jButtonEliminar.setBackground(new java.awt.Color(170, 60, 60));
        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setFocusPainted(false);
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 425, 130, 40));

        jButtonLimpiar.setBackground(new java.awt.Color(140, 140, 140));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setFocusPainted(false);
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 425, 130, 40));

        jButtonVolver.setBackground(new java.awt.Color(80, 80, 80));
        jButtonVolver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.setFocusPainted(false);
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 425, 120, 40));

        setSize(new java.awt.Dimension(716, 510));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPalabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAñadir;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonLimpiar;
    public javax.swing.JButton jButtonModificar;
    public javax.swing.JButton jButtonVolver;
    public javax.swing.JComboBox<Categoria> jComboBoxCategoria;
    public javax.swing.JComboBox<Integer> jComboBoxDificultad;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDificultad;
    private javax.swing.JLabel jLabelPalabra;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPaneTabla;
    public javax.swing.JTable jTablePalabras;
    public javax.swing.JTextField jTextFieldPalabra;
    private javax.swing.JPanel panelForm;
    // End of variables declaration//GEN-END:variables
}
