/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEEPGAMING
 */
public class GestionUsuarios extends javax.swing.JFrame {

    public DefaultTableModel modeloTabla;

    /**
     * Creates new form GestionUsuarios
     */
    public GestionUsuarios() {
        initComponents();
        String[] columnas = {"ID", "Nombre", "Victorias", "Partidas", "Racha actual", "Mejor racha", "Registro"};
        modeloTabla = new DefaultTableModel(columnas, 0);
        jTableUsuarios.setModel(modeloTabla);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        panelForm = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelVictorias = new javax.swing.JLabel();
        jTextFieldVictorias = new javax.swing.JTextField();
        jLabelPartidas = new javax.swing.JLabel();
        jTextFieldPartidas = new javax.swing.JTextField();
        jLabelRachaActual = new javax.swing.JLabel();
        jTextFieldRachaActual = new javax.swing.JTextField();
        jLabelMejorRacha = new javax.swing.JLabel();
        jTextFieldMejorRacha = new javax.swing.JTextField();
        jButtonAñadir = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Usuarios");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(60, 90, 150));
        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("GESTIÓN DE USUARIOS");
        jLabelTitulo.setOpaque(true);
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 45));

        jTableUsuarios.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTableUsuarios.setRowHeight(24);
        jScrollPaneTabla.setViewportView(jTableUsuarios);
        getContentPane().add(jScrollPaneTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 860, 300));

        panelForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));
        panelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setText("Nombre:");
        panelForm.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 25));
        panelForm.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 130, 28));

        jLabelVictorias.setText("Victorias:");
        panelForm.add(jLabelVictorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 30, 60, 25));
        panelForm.add(jTextFieldVictorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 30, 60, 28));

        jLabelPartidas.setText("Partidas:");
        panelForm.add(jLabelPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 60, 25));
        panelForm.add(jTextFieldPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 60, 28));

        jLabelRachaActual.setText("Racha actual:");
        panelForm.add(jLabelRachaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 30, 85, 25));
        panelForm.add(jTextFieldRachaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 60, 28));

        jLabelMejorRacha.setText("Mejor racha:");
        panelForm.add(jLabelMejorRacha, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 30, 80, 25));
        panelForm.add(jTextFieldMejorRacha, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 30, 60, 28));

        getContentPane().add(panelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 860, 75));

        jButtonAñadir.setBackground(new java.awt.Color(70, 140, 70));
        jButtonAñadir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonAñadir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAñadir.setText("Añadir");
        jButtonAñadir.setFocusPainted(false);
        getContentPane().add(jButtonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 165, 40));

        jButtonModificar.setBackground(new java.awt.Color(60, 90, 150));
        jButtonModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("Modificar");
        jButtonModificar.setFocusPainted(false);
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 450, 165, 40));

        jButtonEliminar.setBackground(new java.awt.Color(170, 60, 60));
        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setFocusPainted(false);
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 165, 40));

        jButtonLimpiar.setBackground(new java.awt.Color(140, 140, 140));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setFocusPainted(false);
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 450, 165, 40));

        jButtonVolver.setBackground(new java.awt.Color(80, 80, 80));
        jButtonVolver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.setFocusPainted(false);
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 160, 40));

        setSize(new java.awt.Dimension(896, 540));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAñadir;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonLimpiar;
    public javax.swing.JButton jButtonModificar;
    public javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelMejorRacha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPartidas;
    private javax.swing.JLabel jLabelRachaActual;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVictorias;
    private javax.swing.JScrollPane jScrollPaneTabla;
    public javax.swing.JTable jTableUsuarios;
    public javax.swing.JTextField jTextFieldMejorRacha;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldPartidas;
    public javax.swing.JTextField jTextFieldRachaActual;
    public javax.swing.JTextField jTextFieldVictorias;
    private javax.swing.JPanel panelForm;
    // End of variables declaration//GEN-END:variables
}
