/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEEPGAMING
 */
public class Historial extends javax.swing.JFrame {

    public DefaultTableModel modeloTabla;

    /**
     * Creates new form Historial
     */
    public Historial() {
        initComponents();
        String[] columnas = {"ID", "Usuario", "Palabra", "Long.", "Intentos", "Ganada", "Tiempo (s)", "Fecha"};
        modeloTabla = new DefaultTableModel(columnas, 0);
        jTablePartidas.setModel(modeloTabla);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTablePartidas = new javax.swing.JTable();
        jButtonRefrescar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial de Partidas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(60, 90, 150));
        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("HISTORIAL DE PARTIDAS");
        jLabelTitulo.setOpaque(true);
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 45));

        jTablePartidas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTablePartidas.setRowHeight(24);
        jScrollPaneTabla.setViewportView(jTablePartidas);
        getContentPane().add(jScrollPaneTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 820, 380));

        jButtonRefrescar.setBackground(new java.awt.Color(60, 90, 150));
        jButtonRefrescar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRefrescar.setText("Refrescar");
        jButtonRefrescar.setFocusPainted(false);
        getContentPane().add(jButtonRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 445, 265, 40));

        jButtonEliminar.setBackground(new java.awt.Color(170, 60, 60));
        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setFocusPainted(false);
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 445, 265, 40));

        jButtonVolver.setBackground(new java.awt.Color(80, 80, 80));
        jButtonVolver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.setFocusPainted(false);
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 445, 270, 40));

        setSize(new java.awt.Dimension(856, 535));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonRefrescar;
    public javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPaneTabla;
    public javax.swing.JTable jTablePartidas;
    // End of variables declaration//GEN-END:variables
}
