/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author DEEPGAMING
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal1
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonJugar = new javax.swing.JButton();
        jButtonPalabras = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonHistorial = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(960, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuPrincipal.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonJugar.setBorderPainted(false);
        jButtonJugar.setContentAreaFilled(false);
        jButtonJugar.setFocusPainted(false);
        jButtonJugar.setRolloverEnabled(false);
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 173, 280, 50));

        jButtonPalabras.setBorderPainted(false);
        jButtonPalabras.setContentAreaFilled(false);
        jButtonPalabras.setFocusPainted(false);
        jButtonPalabras.setRolloverEnabled(false);
        jButtonPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalabrasActionPerformed(evt);
            }
        });
        add(jButtonPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 233, 280, 50));

        jButtonUsuarios.setText("jButton1");
        jButtonUsuarios.setBorderPainted(false);
        jButtonUsuarios.setContentAreaFilled(false);
        jButtonUsuarios.setFocusPainted(false);
        jButtonUsuarios.setRolloverEnabled(false);
        jButtonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosActionPerformed(evt);
            }
        });
        add(jButtonUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 290, 50));

        jButtonHistorial.setText("jButton1");
        jButtonHistorial.setBorderPainted(false);
        jButtonHistorial.setContentAreaFilled(false);
        jButtonHistorial.setFocusPainted(false);
        jButtonHistorial.setRolloverEnabled(false);
        jButtonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistorialActionPerformed(evt);
            }
        });
        add(jButtonHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 280, 50));

        jButtonSalir.setText("jButton1");
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setFocusPainted(false);
        jButtonSalir.setRolloverEnabled(false);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 280, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPalabrasActionPerformed

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHistorialActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonHistorial;
    public javax.swing.JButton jButtonJugar;
    public javax.swing.JButton jButtonPalabras;
    public javax.swing.JButton jButtonSalir;
    public javax.swing.JButton jButtonUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
