/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author DEEPGAMING
 */
public class PartidaWordle extends javax.swing.JFrame {

    public JLabel[][] casillas;
    public JLabel[] teclado;

    private int longitud;

    public PartidaWordle() {
        this(5);
    }

    public PartidaWordle(int longitud) {
        this.longitud = longitud;
        initComponents();
        construirTablero();
        construirTeclado();
        setTitle("WORDLE - " + longitud + " letras");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jLabelModo = new javax.swing.JLabel();
        jLabelStats = new javax.swing.JLabel();
        panelTablero = new javax.swing.JPanel();
        panelTeclado = new javax.swing.JPanel();
        jLabelInfo = new javax.swing.JLabel();
        jTextFieldIntento = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jButtonPista = new javax.swing.JButton();
        jButtonRendirse = new javax.swing.JButton();
        jButtonNuevaPartida = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WORDLE");
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setBackground(new java.awt.Color(60, 90, 150));
        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuario.setText("Jugador: -");
        jLabelUsuario.setOpaque(true);
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        jLabelModo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelModo.setForeground(new java.awt.Color(60, 90, 150));
        jLabelModo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModo.setText("Modo: -");
        getContentPane().add(jLabelModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 640, 20));

        jLabelStats.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelStats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStats.setText(" ");
        jLabelStats.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadísticas del jugador"));
        getContentPane().add(jLabelStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 600, 40));

        panelTablero.setBackground(new java.awt.Color(255, 255, 255));
        panelTablero.setLayout(new java.awt.GridLayout(6, 5, 5, 5));
        getContentPane().add(panelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 500, 340));

        panelTeclado.setBackground(new java.awt.Color(255, 255, 255));
        panelTeclado.setBorder(javax.swing.BorderFactory.createTitledBorder("Letras"));
        panelTeclado.setLayout(new java.awt.GridLayout(2, 13, 2, 2));
        getContentPane().add(panelTeclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 600, 80));

        jLabelInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("Escribe una palabra");
        getContentPane().add(jLabelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 600, 20));

        jTextFieldIntento.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        getContentPane().add(jTextFieldIntento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 180, 32));

        jButtonEnviar.setBackground(new java.awt.Color(60, 90, 150));
        jButtonEnviar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.setFocusPainted(false);
        getContentPane().add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 100, 32));

        jButtonPista.setBackground(new java.awt.Color(220, 180, 60));
        jButtonPista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonPista.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPista.setText("Pista");
        jButtonPista.setFocusPainted(false);
        getContentPane().add(jButtonPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 90, 32));

        jButtonRendirse.setBackground(new java.awt.Color(170, 60, 60));
        jButtonRendirse.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonRendirse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRendirse.setText("Rendirse");
        jButtonRendirse.setFocusPainted(false);
        getContentPane().add(jButtonRendirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 100, 32));

        jButtonNuevaPartida.setBackground(new java.awt.Color(70, 140, 70));
        jButtonNuevaPartida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonNuevaPartida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevaPartida.setText("Jugar de nuevo");
        jButtonNuevaPartida.setEnabled(false);
        jButtonNuevaPartida.setFocusPainted(false);
        getContentPane().add(jButtonNuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 220, 40));

        jButtonVolver.setBackground(new java.awt.Color(80, 80, 80));
        jButtonVolver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.setFocusPainted(false);
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 220, 40));

        setSize(new java.awt.Dimension(660, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void construirTablero() {
        panelTablero.removeAll();
        panelTablero.setLayout(new GridLayout(6, longitud, 5, 5));
        casillas = new JLabel[6][longitud];
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < longitud; j++) {
                JLabel l = new JLabel("", SwingConstants.CENTER);
                l.setOpaque(true);
                l.setBackground(Color.WHITE);
                l.setBorder(BorderFactory.createLineBorder(new Color(180, 180, 180), 2));
                l.setFont(new Font("Arial", Font.BOLD, 24));
                l.setPreferredSize(new Dimension(50, 50));
                casillas[i][j] = l;
                panelTablero.add(l);
            }
        }
    }

    private void construirTeclado() {
        panelTeclado.removeAll();
        teclado = new JLabel[26];
        for (int i = 0; i < 26; i++) {
            char c = (char) ('A' + i);
            JLabel l = new JLabel(String.valueOf(c), SwingConstants.CENTER);
            l.setOpaque(true);
            l.setBackground(Color.WHITE);
            l.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));
            l.setFont(new Font("Arial", Font.BOLD, 13));
            l.setPreferredSize(new Dimension(28, 28));
            teclado[i] = l;
            panelTeclado.add(l);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartidaWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartidaWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartidaWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartidaWordle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartidaWordle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonEnviar;
    public javax.swing.JButton jButtonNuevaPartida;
    public javax.swing.JButton jButtonPista;
    public javax.swing.JButton jButtonRendirse;
    public javax.swing.JButton jButtonVolver;
    public javax.swing.JLabel jLabelInfo;
    public javax.swing.JLabel jLabelModo;
    public javax.swing.JLabel jLabelStats;
    public javax.swing.JLabel jLabelUsuario;
    public javax.swing.JTextField jTextFieldIntento;
    public javax.swing.JPanel panelTablero;
    public javax.swing.JPanel panelTeclado;
    // End of variables declaration//GEN-END:variables
}
