/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author DEEPGAMING
 */
public class SeleccionModo extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionModo1
     */
    public SeleccionModo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton4Letras = new javax.swing.JButton();
        jButton5Letras = new javax.swing.JButton();
        jButton6Letras = new javax.swing.JButton();
        jButtonFacil = new javax.swing.JButton();
        jButtonDificil = new javax.swing.JButton();
        jButtonEmpezar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SeleccionModo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton4Letras.setBorderPainted(false);
        jButton4Letras.setContentAreaFilled(false);
        jButton4Letras.setFocusPainted(false);
        jButton4Letras.setRolloverEnabled(false);
        jButton4Letras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4LetrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4Letras, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 90));

        jButton5Letras.setBorderPainted(false);
        jButton5Letras.setContentAreaFilled(false);
        jButton5Letras.setFocusPainted(false);
        jButton5Letras.setRolloverEnabled(false);
        getContentPane().add(jButton5Letras, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 200, 90));

        jButton6Letras.setBorderPainted(false);
        jButton6Letras.setContentAreaFilled(false);
        jButton6Letras.setFocusPainted(false);
        jButton6Letras.setRolloverEnabled(false);
        getContentPane().add(jButton6Letras, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 145, 210, 90));

        jButtonFacil.setBorderPainted(false);
        jButtonFacil.setContentAreaFilled(false);
        jButtonFacil.setFocusPainted(false);
        jButtonFacil.setRolloverEnabled(false);
        getContentPane().add(jButtonFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 240, 80));

        jButtonDificil.setBorderPainted(false);
        jButtonDificil.setContentAreaFilled(false);
        jButtonDificil.setFocusPainted(false);
        jButtonDificil.setRolloverEnabled(false);
        getContentPane().add(jButtonDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 295, 230, 90));

        jButtonEmpezar.setBorderPainted(false);
        jButtonEmpezar.setContentAreaFilled(false);
        jButtonEmpezar.setFocusPainted(false);
        jButtonEmpezar.setRolloverEnabled(false);
        getContentPane().add(jButtonEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 415, 395, 85));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4LetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4LetrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4LetrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionModo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton4Letras;
    public javax.swing.JButton jButton5Letras;
    public javax.swing.JButton jButton6Letras;
    public javax.swing.JButton jButtonDificil;
    public javax.swing.JButton jButtonEmpezar;
    public javax.swing.JButton jButtonFacil;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
